import 'package:flutter/material.dart';

class Product {
  final String id; // Auto-generated by DB or UUID
  final String name;
  final String description;
  final String location; // Vendor/Shop name
  final double price;
  final String? imageUrl;
  final String category; // e.g., 'handicraft', 'food_product'
  final String? city; // Optional: City where the product is available

  Product({
    required this.id,
    required this.name,
    required this.description,
    required this.location,
    required this.price,
    this.imageUrl,
    required this.category,
    this.city,
  });

  // Factory constructor to create a Product from JSON (database row)
  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
      id: json['id'] as String,
      name: json['name'] as String,
      description: json['description'] as String,
      location: json['location'] as String,
      // Ensure price is parsed correctly, handling potential String from DB
      price: (json['price'] is String) 
             ? (double.tryParse(json['price']) ?? 0.0) 
             : (json['price'] as num? ?? 0.0).toDouble(),
      imageUrl: json['image_url'] as String?,
      category: json['category'] as String,
      city: json['city'] as String?,
    );
  }

  // Method to convert Product to JSON (for inserting into database)
  Map<String, dynamic> toJson() {
    return {
      // 'id' is usually handled by the database (e.g., auto-increment or UUID)
      'name': name,
      'description': description,
      'location': location,
      'price': price,
      'image_url': imageUrl,
      'category': category,
      'city': city,
    };
  }
}
